<?php
require_once './src/db_config.php';
require_once './src/auth.php';
require_once  './src/functions.php';

require_admin();

global $db;
$view = $_GET['view'] ?? 'requests';
$search = $_GET['search'] ?? '';
$message = "";

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    if ($_POST['action'] === 'delete_request' && isset($_POST['idR'])) {
        $stmt = $db->prepare("DELETE FROM HelpRequests WHERE idR = ?");
        $stmt->execute([$_POST['idR']]);
        $message = "Demande supprimée.";
    }

    if ($_POST['action'] === 'delete_user' && isset($_POST['user_id'])) {
        $stmt = $db->prepare("DELETE FROM User WHERE user_id = ?");
        $stmt->execute([$_POST['user_id']]);
        $message = "Utilisateur supprimé.";
    }
}

if ($view === 'users') {
    $sql = "SELECT User.user_id, User.email, defUser.fName, defUser.sName, defUser.tel 
            FROM User
            JOIN defUser ON User.user_id = defUser.user_id";
    if (!empty($search)) {
        $stmt = $db->prepare($sql . " WHERE defUser.fName LIKE :search OR defUser.sName LIKE :search");
        $stmt->execute(['search' => "%$search%"]);
        $data = $stmt->fetchAll();
    } else {
        $data = $db->query($sql)->fetchAll();
    }
} else {
    $sql = "SELECT HelpRequests.*, defUser.fName, defUser.sName 
            FROM HelpRequests 
            JOIN defUser ON HelpRequests.inNeed_id = defUser.user_id";
    if (!empty($search)) {
        $stmt = $db->prepare($sql . " WHERE du.fName LIKE :search OR du.sName LIKE :search ORDER BY hr.created_at DESC");
        $stmt->execute(['search' => "%$search%"]);
        $data = $stmt->fetchAll();
    } else {
        $data = $db->query($sql . " ORDER BY HelpRequests.created_at DESC")->fetchAll();
    }
}
?>
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE-->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<!-- PERFECT HTML AND CSS GENERATED BY AI = TO CHANGE -->
<div class="admin-layout">
    <nav class="admin-sidebar">
        <div class="sidebar-header">
            <h3>MainsTendues</h3>
        </div>
        <ul class="nav-links">
            <li class="<?php echo $view === 'requests' ? 'active' : ''; ?>">
                <a href="index.php?page=profileADM&view=requests"><i class="fas fa-hand-holding-heart"></i> Demandes</a>
            </li>
            <li class="<?php echo $view === 'users' ? 'active' : ''; ?>">
                <a href="index.php?page=profileADM&view=users"><i class="fas fa-users"></i> Utilisateurs</a>
            </li>
            <li>
                <a href="index.php?page=logout" class="logout-link"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </nav>

    <main class="admin-main">
        <?php if ($message): ?>
            <div class="alert"><?php echo $message; ?></div>
        <?php endif; ?>

        <header class="content-header">
            <h1><?php echo $view === 'users' ? 'Utilisateurs' : 'Demandes d\'aide'; ?></h1>

            <form method="GET" action="index.php" class="search-form">
                <input type="hidden" name="page" value="profileADM">
                <input type="hidden" name="view" value="<?php echo htmlspecialchars($view); ?>">
                <input type="text" name="search" placeholder="Chercher par nom..." value="<?php echo htmlspecialchars($search); ?>">
                <button type="submit"><i class="fas fa-search"></i></button>
                <?php if ($search): ?>
                    <a href="index.php?page=profileADM&view=<?php echo $view; ?>" class="btn-clear">Effacer</a>
                <?php endif; ?>
            </form>
        </header>

        <table class="admin-table">
            <thead>
            <?php if ($view === 'users'): ?>
                <tr>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            <?php else: ?>
                <tr>
                    <th>Demandeur</th>
                    <th>Type</th>
                    <th>Urgence</th>
                    <th>Actions</th>
                </tr>
            <?php endif; ?>
            </thead>
            <tbody>
            <?php if (empty($data)): ?>
                <tr><td colspan="4" style="text-align:center;">Aucun résultat pour "<?php echo htmlspecialchars($search); ?>".</td></tr>
            <?php else: ?>
                <?php foreach ($data as $row): ?>
                    <tr>
                        <?php if ($view === 'users'): ?>
                            <td><?php echo htmlspecialchars($row['fName'] . " " . $row['sName']); ?></td>
                            <td><?php echo htmlspecialchars($row['email']); ?></td>
                            <td>
                                <form method="POST" onsubmit="return confirm('Supprimer cet utilisateur ?');">
                                    <input type="hidden" name="action" value="delete_user">
                                    <input type="hidden" name="user_id" value="<?php echo $row['user_id']; ?>">
                                    <button type="submit" class="btn-delete"><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        <?php else: ?>
                            <td><?php echo htmlspecialchars($row['fName'] . " " . $row['sName']); ?></td>
                            <td><?php echo htmlspecialchars($row['hType']); ?></td>
                            <!--to add a htmlspecialchars() function after cleaning the data base-->
                            <td><?php echo $row['urgencyLevel']; ?></td>
                            <!--to add a htmlspecialchars() function after cleaning the data base-->
                            <td>
                                <form method="POST" onsubmit="return confirm('Supprimer cette demande ?');">
                                    <input type="hidden" name="action" value="delete_request">
                                    <input type="hidden" name="idR" value="<?php echo $row['idR']; ?>">
                                    <button type="submit" class="btn-delete"><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </main>
</div>
<style>

.admin-layout {
    display: flex;
    min-height: 100vh;
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
}

.admin-sidebar {
    width: 250px;
    background-color: #2c3e50;
    color: white;
    padding: 20px 0;
    position: fixed;
    height: 100vh;
    overflow-y: auto;
    box-shadow: 2px 0 5px rgba(0,0,0,0.1);
}

.sidebar-header {
    text-align: center;
    margin-bottom: 30px;
    padding: 0 20px;
}

.sidebar-header h3 {
    margin: 0;
    font-size: 24px;
    color: #ecf0f1;
}

.nav-links {
    list-style: none;
    padding: 0;
    margin: 0;
}

.nav-links li {
    margin: 5px 0;
}

.nav-links a {
    display: block;
    padding: 15px 20px;
    color: #bdc3c7;
    text-decoration: none;
    transition: all 0.3s ease;
    border-left: 3px solid transparent;
}

.nav-links a:hover {
    background-color: #34495e;
    color: #ecf0f1;
    border-left-color: #3498db;
}

.nav-links .active a {
    background-color: #3498db;
    color: white;
    border-left-color: #2980b9;
}

.logout-link {
    margin-top: 30px;
    border-top: 1px solid #34495e;
    padding-top: 20px;
}

.logout-link a {
    color: #e74c3c;
}

.logout-link a:hover {
    background-color: #c0392b;
    color: white;
}

.admin-main {
    margin-left: 250px;
    flex: 1;
    padding: 30px;
    background-color: #f4f4f4;
}

.content-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    background: white;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.content-header h1 {
    margin: 0;
    color: #2c3e50;
    font-size: 28px;
}

.search-form {
    display: flex;
    align-items: center;
    gap: 10px;
}

.search-form input[type="text"] {
    padding: 10px 15px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 14px;
    width: 250px;
}

.search-form button {
    padding: 10px 15px;
    background-color: #3498db;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.search-form button:hover {
    background-color: #2980b9;
}

.btn-clear {
    padding: 10px 15px;
    background-color: #95a5a6;
    color: white;
    text-decoration: none;
    border-radius: 4px;
    font-size: 14px;
    transition: background-color 0.3s ease;
}

.btn-clear:hover {
    background-color: #7f8c8d;
}

.alert {
    background-color: #d4edda;
    color: #155724;
    padding: 15px;
    border: 1px solid #c3e6cb;
    border-radius: 4px;
    margin-bottom: 20px;
    font-weight: bold;
}

.admin-table {
    width: 100%;
    border-collapse: collapse;
    background: white;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.admin-table thead {
    background-color: #2c3e50;
    color: white;
}

.admin-table th,
.admin-table td {
    padding: 15px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

.admin-table th {
    font-weight: 600;
    font-size: 14px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.admin-table tbody tr:hover {
    background-color: #f8f9fa;
}

.admin-table tbody tr:last-child td {
    border-bottom: none;
}

.btn-delete {
    background-color: #e74c3c;
    color: white;
    border: none;
    padding: 8px 12px;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
    font-size: 14px;
}

.btn-delete:hover {
    background-color: #c0392b;
}

.btn-delete i {
    margin-right: 5px;
}

@media (max-width: 768px) {
    .admin-layout {
        flex-direction: column;
    }

    .admin-sidebar {
        position: static;
        width: 100%;
        height: auto;
        padding: 10px 0;
    }

    .admin-main {
        margin-left: 0;
        padding: 20px;
    }

    .content-header {
        flex-direction: column;
        align-items: flex-start;
        gap: 15px;
    }

    .search-form {
        width: 100%;
    }

    .search-form input[type="text"] {
        width: 100%;
        max-width: none;
    }

    .admin-table {
        font-size: 14px;
    }

    .admin-table th,
    .admin-table td {
        padding: 10px;
    }
}

@media (max-width: 480px) {
    .admin-sidebar {
        padding: 10px;
    }

    .nav-links a {
        padding: 12px 15px;
        font-size: 14px;
    }

    .admin-main {
        padding: 15px;
    }

    .content-header h1 {
        font-size: 24px;
    }
}
</style>